dataset:
  train_dataset: ./data/aiwin/splited_train_data.txt
  eval_dataset: ./data/aiwin/splited_eval_data.txt
  predict_dataset: ./data/aiwin/eval_dataset.txt
  label_dir: ./data/aiwin/label.txt

model:
  pretrained_name_or_path: hfl/chinese-electra-180g-small-discriminator # uer/albert-base-chinese-cluecorpussmall

run:
  device_id: '-1' # 使用cpu则置为-1

train:
  train_epochs: 1
  per_device_batch_size: 1
  logging_steps: 20
  eval_steps: 32

  select_model_metric: 'macro_f1'

  use_class_weight: True # 是否按类别数量权重更新loss
  class_weight_max_scale_ratio: 10.0 # 最大扩充比例

  use_adversarial: True # 默认FGM

  max_length: 32 #最长字数限制

  learning_rate: 3.0e-5
  gradient_accumulation_steps: 2
  warmup_ratio: 0.01
  max_grad_norm: 1.0
  weight_decay: 0.01

  adam_epsilon: 1e-8






